import type { Commands } from "./types.js";

export interface CommandSpec<K extends keyof Commands = keyof Commands> {
  method: K;
  ipc: string;
  http: string;
  bodyKeys: readonly string[];
}

export const COMMANDS = [
  { method: "openRepo", ipc: "open_repo", http: "/repo/open", bodyKeys: ["path"] },
  { method: "getLog", ipc: "get_log", http: "/log", bodyKeys: ["repoPath", "filter"] },
  { method: "getCommitDetail", ipc: "get_commit_detail", http: "/commit/detail", bodyKeys: ["repoPath", "commitId"] },
  { method: "getCommitFiles", ipc: "get_commit_files", http: "/commit/files", bodyKeys: ["repoPath", "commitId"] },
  { method: "getCommitDiff", ipc: "get_commit_diff", http: "/commit/diff", bodyKeys: ["repoPath", "commitId", "filePath"] },
  { method: "getFileDiff", ipc: "get_file_diff", http: "/file/diff", bodyKeys: ["repoPath", "filePath", "staged"] },
  { method: "compareCommits", ipc: "compare_commits", http: "/commits/compare", bodyKeys: ["repoPath", "fromId", "toId"] },
  { method: "getBranches", ipc: "get_branches", http: "/branches", bodyKeys: ["repoPath"] },
  { method: "createBranch", ipc: "create_branch", http: "/branch/create", bodyKeys: ["repoPath", "name", "startPoint"] },
  { method: "checkoutBranch", ipc: "checkout_branch", http: "/branch/checkout", bodyKeys: ["repoPath", "name"] },
  { method: "forceCheckoutBranch", ipc: "force_checkout_branch", http: "/branch/checkout-force", bodyKeys: ["repoPath", "name"] },
  { method: "smartCheckoutBranch", ipc: "smart_checkout_branch", http: "/branch/checkout-smart", bodyKeys: ["repoPath", "name"] },
  { method: "previewCheckoutConflicts", ipc: "preview_checkout_conflicts", http: "/branch/checkout-preview", bodyKeys: ["repoPath", "branch", "dirtyFiles"] },
  { method: "deleteBranch", ipc: "delete_branch", http: "/branch/delete", bodyKeys: ["repoPath", "name", "force"] },
  { method: "renameBranch", ipc: "rename_branch", http: "/branch/rename", bodyKeys: ["repoPath", "oldName", "newName"] },
  { method: "mergeBranch", ipc: "merge_branch", http: "/branch/merge", bodyKeys: ["repoPath", "name"] },
  { method: "rebaseBranch", ipc: "rebase_branch", http: "/branch/rebase", bodyKeys: ["repoPath", "upstream"] },
  { method: "cherryPick", ipc: "cherry_pick", http: "/cherry-pick", bodyKeys: ["repoPath", "commitId"] },
  { method: "cherryPickRange", ipc: "cherry_pick_range", http: "/cherry-pick/range", bodyKeys: ["repoPath", "commitIds"] },
  { method: "rebaseAutosquash", ipc: "rebase_autosquash", http: "/branch/rebase-autosquash", bodyKeys: ["repoPath", "upstream"] },
  { method: "revertCommit", ipc: "revert_commit", http: "/commit/revert", bodyKeys: ["repoPath", "commitId"] },
  { method: "resetToCommit", ipc: "reset_to_commit", http: "/commit/reset", bodyKeys: ["repoPath", "commitId", "mode"] },
  { method: "squashCommits", ipc: "squash_commits", http: "/commits/squash", bodyKeys: ["repoPath", "count", "message"] },
  { method: "getRebaseTodoPreview", ipc: "get_rebase_todo_preview", http: "/rebase/todo-preview", bodyKeys: ["repoPath", "baseRef"] },
  { method: "startInteractiveRebase", ipc: "start_interactive_rebase", http: "/rebase/interactive", bodyKeys: ["repoPath", "baseRef", "todos"] },
  { method: "getRebaseStatus", ipc: "get_rebase_status", http: "/rebase/status", bodyKeys: ["repoPath"] },
  { method: "getStatus", ipc: "get_status", http: "/status", bodyKeys: ["repoPath"] },
  { method: "stageFile", ipc: "stage_file", http: "/stage/file", bodyKeys: ["repoPath", "filePath"] },
  { method: "unstageFile", ipc: "unstage_file", http: "/unstage/file", bodyKeys: ["repoPath", "filePath"] },
  { method: "stageAll", ipc: "stage_all", http: "/stage/all", bodyKeys: ["repoPath"] },
  { method: "unstageAll", ipc: "unstage_all", http: "/unstage/all", bodyKeys: ["repoPath"] },
  { method: "stageFilesBatch", ipc: "stage_files_batch", http: "/stage/files-batch", bodyKeys: ["repoPath", "filePaths"] },
  { method: "unstageFilesBatch", ipc: "unstage_files_batch", http: "/unstage/files-batch", bodyKeys: ["repoPath", "filePaths"] },
  { method: "addToGitignore", ipc: "add_to_gitignore", http: "/gitignore/add", bodyKeys: ["repoPath", "filePath"] },
  { method: "listWorktrees", ipc: "worktree_list", http: "/worktree/list", bodyKeys: ["repoPath"] },
  { method: "addWorktree", ipc: "worktree_add", http: "/worktree/add", bodyKeys: ["repoPath", "targetPath", "branchOrCommit", "createBranch"] },
  { method: "removeWorktree", ipc: "worktree_remove", http: "/worktree/remove", bodyKeys: ["repoPath", "targetPath", "force"] },
  { method: "lockWorktree", ipc: "worktree_lock", http: "/worktree/lock", bodyKeys: ["repoPath", "targetPath", "reason"] },
  { method: "unlockWorktree", ipc: "worktree_unlock", http: "/worktree/unlock", bodyKeys: ["repoPath", "targetPath"] },
  { method: "pruneWorktrees", ipc: "worktree_prune", http: "/worktree/prune", bodyKeys: ["repoPath"] },
  { method: "listHooks", ipc: "hooks_list", http: "/hooks/list", bodyKeys: ["repoPath"] },
  { method: "readHookContent", ipc: "hooks_read", http: "/hooks/read", bodyKeys: ["repoPath", "hookName"] },
  { method: "writeHookContent", ipc: "hooks_write", http: "/hooks/write", bodyKeys: ["repoPath", "hookName", "content"] },
  { method: "enableHook", ipc: "hooks_enable", http: "/hooks/enable", bodyKeys: ["repoPath", "hookName"] },
  { method: "disableHook", ipc: "hooks_disable", http: "/hooks/disable", bodyKeys: ["repoPath", "hookName"] },
  { method: "commit", ipc: "commit", http: "/commit", bodyKeys: ["repoPath", "message", "amend"] },
  { method: "commitFixup", ipc: "commit_fixup", http: "/commit-fixup", bodyKeys: ["repoPath", "commitId"] },
  { method: "commitFiles", ipc: "commit_files", http: "/commit-files", bodyKeys: ["repoPath", "filePaths", "message"] },
  { method: "push", ipc: "push_remote", http: "/push", bodyKeys: ["repoPath", "remote", "branch", "options"] },
  { method: "getUnpushedCommits", ipc: "get_unpushed_commits", http: "/unpushed-commits", bodyKeys: ["repoPath", "remote", "branch"] },
  { method: "getBehindCount", ipc: "get_behind_count", http: "/behind-count", bodyKeys: ["repoPath", "remote", "branch"] },
  { method: "pull", ipc: "pull_remote", http: "/pull", bodyKeys: ["repoPath", "remote", "rebase"] },
  { method: "previewPullConflicts", ipc: "preview_pull_conflicts", http: "/pull/preview", bodyKeys: ["repoPath", "remote"] },
  { method: "forcePull", ipc: "force_pull", http: "/pull/force", bodyKeys: ["repoPath", "remote", "rebase"] },
  { method: "fetch", ipc: "fetch_remote", http: "/fetch", bodyKeys: ["repoPath", "remote"] },
  { method: "fetchAll", ipc: "fetch_all", http: "/fetch/all", bodyKeys: ["repoPath"] },
  { method: "fetchBranch", ipc: "fetch_branch", http: "/branch/fetch-update", bodyKeys: ["repoPath", "remote", "branchName"] },
  { method: "getRemotes", ipc: "get_remotes", http: "/remotes", bodyKeys: ["repoPath"] },
  { method: "getStashList", ipc: "get_stash_list", http: "/stash/list", bodyKeys: ["repoPath"] },
  { method: "stashSave", ipc: "stash_save", http: "/stash/save", bodyKeys: ["repoPath", "message", "includeUntracked"] },
  { method: "stashApply", ipc: "stash_apply", http: "/stash/apply", bodyKeys: ["repoPath", "index"] },
  { method: "stashPop", ipc: "stash_pop", http: "/stash/pop", bodyKeys: ["repoPath", "index"] },
  { method: "stashDrop", ipc: "stash_drop", http: "/stash/drop", bodyKeys: ["repoPath", "index"] },
  { method: "stashRename", ipc: "stash_rename", http: "/stash/rename", bodyKeys: ["repoPath", "index", "newMessage"] },
  { method: "getStashFiles", ipc: "get_stash_files", http: "/stash/files", bodyKeys: ["repoPath", "index"] },
  { method: "getStashFileDiff", ipc: "get_stash_file_diff", http: "/stash/file-diff", bodyKeys: ["repoPath", "index", "filePath"] },
  { method: "getBlame", ipc: "get_blame", http: "/blame", bodyKeys: ["repoPath", "filePath", "commitId"] },
  { method: "getConflictFiles", ipc: "get_conflict_files", http: "/conflict/files", bodyKeys: ["repoPath"] },
  { method: "getConflictContent", ipc: "get_conflict_content", http: "/conflict/content", bodyKeys: ["repoPath", "filePath"] },
  { method: "resolveConflict", ipc: "resolve_conflict", http: "/conflict/resolve", bodyKeys: ["repoPath", "filePath", "content"] },
  { method: "getWorkingFileContent", ipc: "get_working_file_content", http: "/conflict/working-content", bodyKeys: ["repoPath", "filePath"] },
  { method: "getMergeState", ipc: "get_merge_state", http: "/merge-state", bodyKeys: ["repoPath"] },
  { method: "continueOperation", ipc: "continue_operation", http: "/merge-op/continue", bodyKeys: ["repoPath", "op"] },
  { method: "abortOperation", ipc: "abort_operation", http: "/merge-op/abort", bodyKeys: ["repoPath", "op"] },
  { method: "cloneRepo", ipc: "clone_repo", http: "/clone", bodyKeys: ["url", "path"] },
  { method: "getFileContent", ipc: "get_file_content", http: "/file/content", bodyKeys: ["repoPath", "commitId", "filePath"] },
  { method: "discardFileChanges", ipc: "discard_file_changes", http: "/file/discard", bodyKeys: ["repoPath", "filePath"] },
  { method: "getFileDiffRaw", ipc: "get_file_diff_raw", http: "/file/diff-raw", bodyKeys: ["repoPath", "filePath", "staged"] },
  { method: "deleteFile", ipc: "delete_file", http: "/file/delete", bodyKeys: ["repoPath", "filePath"] },
  { method: "stashFile", ipc: "stash_file", http: "/stash/file", bodyKeys: ["repoPath", "filePath", "message"] },
  { method: "stashFiles", ipc: "stash_files", http: "/stash/files-batch", bodyKeys: ["repoPath", "filePaths", "message"] },
  { method: "createTag", ipc: "create_tag", http: "/tag/create", bodyKeys: ["repoPath", "name", "commitId", "message"] },
  { method: "deleteTag", ipc: "delete_tag", http: "/tag/delete", bodyKeys: ["repoPath", "name"] },
  { method: "pushTag", ipc: "push_tag", http: "/tag/push", bodyKeys: ["repoPath", "remote", "name"] },
  { method: "deleteRemoteTag", ipc: "delete_remote_tag", http: "/tag/delete-remote", bodyKeys: ["repoPath", "remote", "name"] },
  { method: "checkoutTag", ipc: "checkout_tag", http: "/tag/checkout", bodyKeys: ["repoPath", "name"] },
  { method: "getReflog", ipc: "get_reflog", http: "/reflog", bodyKeys: ["repoPath", "limit"] },
  { method: "createPatch", ipc: "create_patch", http: "/patch/create", bodyKeys: ["repoPath", "commitId"] },
  { method: "applyPatch", ipc: "apply_patch", http: "/patch/apply", bodyKeys: ["repoPath", "patchContent"] },
  { method: "getSubmodules", ipc: "get_submodules", http: "/submodules", bodyKeys: ["repoPath"] },
  { method: "initSubmodules", ipc: "init_submodules", http: "/submodules/init", bodyKeys: ["repoPath", "paths"] },
  { method: "updateSubmodules", ipc: "update_submodules", http: "/submodules/update", bodyKeys: ["repoPath", "paths"] },
  { method: "syncSubmodules", ipc: "sync_submodules", http: "/submodules/sync", bodyKeys: ["repoPath", "paths"] },
] as const satisfies readonly CommandSpec[];

export type CommandMethod = (typeof COMMANDS)[number]["method"];
